name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Confirma o destroy da infraestrutura?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplandestroy

      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve tfplandestroy
        if: github.event.inputs.destroy == 'true'